FROM alpine AS package
ARG VERSION
COPY optiradar-other-$VERSION.zip /tmp/optiradar.zip
RUN unzip -qo /tmp/optiradar.zip -d /optiradar

FROM eclipse-temurin:25 AS jdk
RUN jlink --add-modules java.se,jdk.charsets,jdk.crypto.ec,jdk.net,jdk.unsupported \
    --strip-debug --no-header-files --no-man-pages --compress=2 --output /jre

FROM ubuntu:latest
COPY --from=package /optiradar /opt/optiradar
COPY --from=jdk /jre /opt/optiradar/jre
WORKDIR /opt/optiradar
ENTRYPOINT ["/opt/optiradar/jre/bin/java", "-XX:+ExitOnOutOfMemoryError"]
CMD ["-jar", "tracker-server.jar", "conf/optiradar.xml"]
